config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  # get 'admin/index'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  
  resources :users  
  get 'store/index'
  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.page_title') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>   
    <div id="banner">
      <%= form_tag store_path, class: 'locale' do %>
        <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()'%>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()"%>
      <% end %>

      <%= image_tag('logo.png') %>
      <%= @page_title || t('.title')%>
    </div>

    <div id="columns">
      <div id="side">        
        <div id="cart">
          <% if @cart %>
            <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %>
            <% end %>
          <% end %>
        </div>
        <ul>        
          <li><a href="/"><%= t('.home') %></a></li>
          <li><a href="/questions"><%= t('.questions') %></a></li>
          <li><a href="/news"><%= t('.news') %></a></li>
          <li><a href="/contact"> <%= t('.contact') %> </a></li>
        </ul>

        <% if session[:user_id ]%>
            <ul>
              <li><%= link_to t('.orders'), orders_path %></li>
              <li><%= link_to t('.products'), products_path %></li>
              <li><%= link_to t('.users'), users_path %></li>
            </ul>

            <%= button_to t('.logout'), logout_path, method: :delete %>
        <% end %>
      </div>
    </div>
    <div id="main" class='<%= controller.controller_name %>'>  
      <%= yield %>      
    </div>
  </body>
</html>